### ISSUE TITLE
simple reveal.js slide with ul rendered wrong

### ISSUE THREAD

**Issue by dirk-thomas** [astefanutti/decktape#127]
I am trying to convert some reveal.js slides to pdf and ran into a problem with the positioning of simple lists. The easiest way to reproduce the problem is to use the latest release of reveal.js and modify the demo slides to contain a few more bullets. E.g. on [this](https://github.com/hakimel/reveal.js/blob/3.6.0/demo.html#L247-L253) slide duplicate the four list items so that the list contains eight items.

In the browser the slide looks good:

![screenshot from 2017-12-17 11-01-02](https://user-images.githubusercontent.com/1335366/34078389-5125c5a6-e2ce-11e7-8f0f-0c11ffe58176.png)

After exporting the slides with decktape the page looks like this:

![decktape](https://user-images.githubusercontent.com/1335366/34078409-b580a818-e2ce-11e7-9dba-ccede78d710f.png)

Any feedback (even if it is a workaround for now) would be highly appreciated. Thanks.

**Comment by astefanutti** [comment]
One work-around that I've just tested and that seems to fix your issue is to adjust the PDF size, e.g., with the `-s 1024x768` option.

I've already noticed some layout issues with the PDF export in Chrome in some specific cases. I've already reported a couple to the Puppeteer team though it doesn't seem high priority (probably because it's more an issue at the level of the PDF printer component that Chrome uses).

I don't see much that can be done at DeckTape level. So if the work-around addresses your issue, I'd be inclined to close this issue.

**Comment by dirk-thomas** [comment]
> One work-around that I've just tested and that seems to fix your issue is to adjust the PDF size, e.g., with the -s 1024x768 option.

That also works for me. Thank you for the hint.

> I've already noticed some layout issues with the PDF export in Chrome in some specific cases. I've already reported a couple to the Puppeteer team though it doesn't seem high priority (probably because it's more an issue at the level of the PDF printer component that Chrome uses).

Do you have references for those issues? Then I can watch / +1 them.

> I don't see much that can be done at DeckTape level. So if the work-around addresses your issue, I'd be inclined to close this issue.

Ok, I understand. Thanks.

**Comment by astefanutti** [comment]
> Do you have references for those issues? Then I can watch / +1 them.

Here are the issues I have created: https://github.com/GoogleChrome/puppeteer/issues/created_by/astefanutti

It's often the same kind of issue, with absolute positioning (scaling and transform), where an element does not render centered in PDF as in screenshot or the browser.
