### ISSUE TITLE
doesn't stop printing slides

### ISSUE THREAD

**Issue by hvwaldow** [astefanutti/decktape#137]
decktape 2.8.0, using the `reveal`command, doesn't stop printing slides.
It perfectly works if I use `--slides 1-n`, where `n` is the number of actual slides.
Using `n` larger than the actual number of slides shows that decktape keeps repeating to print the last slide.

**Comment by ynohat** [comment]
@hvwaldow please check that you are using `<div class="slides">...</div>` as a wrapper, and not `<section class="slides">...</div>` AND that you have no extra content after the wrapper.

I was experiencing the same issue, and it turns out that it was due to the `reveal` plugin using `Reveal.isLastSlide` which returns a wrong value when the wrapper is a `section`:

Decktape / reveal plugin:

```js
  hasNextSlide() {
    // check with fragments option?
    return this.page.evaluate(_ => !Reveal.isLastSlide() || Reveal.availableFragments().next);
  }
```

Reveal / isLastSlide:

```js
		isLastSlide: function() {
			if( currentSlide ) {
				// Does this slide have a next sibling?
				if( currentSlide.nextElementSibling ) return false;

				// If it's vertical, does its parent have a next sibling?
				if( isVerticalSlide( currentSlide ) && currentSlide.parentNode.nextElementSibling ) return false;

				return true;
			}

			return false;
		}
```

Reveal / isVerticalSlide :

```js
	function isVerticalSlide( slide ) {

		// Prefer slide argument, otherwise use current slide
		slide = slide ? slide : currentSlide;

		return slide && slide.parentNode && !!slide.parentNode.nodeName.match( /section/i );

	}
```

I believe that last match is brittle.

**Comment by hvwaldow** [comment]
Thanks @ynohat! Checking that, it turned out that, surprisingly, the problem goes away if I close the wrapping div.  I am embarrassed 😳.

**Comment by astefanutti** [comment]
Thanks a lot @ynohat!
