### ISSUE TITLE
getting TypeError: annotation.toJSObject is not a function

### ISSUE THREAD

**Issue by DanielRuf** [astefanutti/decktape#155]
I am getting `TypeError: annotation.toJSObject is not a function` when I run decktape against the latest reveal.js release using yarn.

**Comment by astefanutti** [comment]
Thanks for the report. It should be fixed in version 2.8.5 with 76eb3e715a1e53c4830159adea340b30bf43d7fd.

It happens Chrome now outputs PDF with links as annotation references as opposed to objects. As you use Yarn, you did not have the compatible version of Puppeteer installed. I've made the fix capable of dealing with whatever link format. So you should be able to keep using Yarn to install DeckTape.

**Comment by DanielRuf** [comment]
It works now =) 👍
