### ISSUE TITLE
RISE 5.3 not working with current `master`

### ISSUE THREAD

**Issue by nilsnolde** [astefanutti/decktape#164]
I'm trying to use `decktape` as described in [RISE docs](https://damianavila.github.io/RISE/usage.html#using-decktape):

`phantomjs decktape.js rise http://localhost:8888/notebooks/src/SOTM18.ipynb?token=token ../../python/sotm2018/sotm18_slides.pdf`

However, that throws the following error:

> SyntaxError: Unexpected token 'const'
> phantomjs://code/decktape.js:5

I followed the previous steps of that guide. Am I missing something crucial?

**Comment by astefanutti** [comment]
The RISE documentation still covers DeckTape 1.x which is deprecated. I would suggest you use DeckTape 2.x. You should be able to follow the installation instructions from that repository and then follow the remaining steps from the RISE documentation.

You may want to vote for damianavila/RISE#374 so that the RISE documentation gets updated.

Let me close that issue. Feel free to ask for more info if needed.
