### ISSUE TITLE
HummusJS no longer maintained

### ISSUE THREAD

**Issue by nicojs** [astefanutti/decktape#204]
HummusJS no longer seems to be maintained.

> Update 9/11/2019 Ending Support:
> Hi All, after 6 years I decided to finish supporting HummusJS. You may still use the code as is, with the provided license, however I will not be providing answers, solutions, responses etc.
I'd like to thank everyone who used HummusJS and wish you all the best going forward with your projects.

Installing decktape on node13 results in the following error:

decktape\node_modules\hummus\src\objectbytereader.cpp(57): error C2661: 'v8::Object::Get': no overloaded function takes 1 arguments [node_modules\decktape\node_modules\hummus\build\hummus.vcxproj]

Is there a plan to migrate to something else? Or fork HummusJS and fixing this issue?

Thanks for the hard work! 🌹

**Comment by astefanutti** [comment]
Thanks a lot for the report. It is similar to #201.

We are still thinking about the best approach to solve this. I'd like to explore the idea of compiling HummusJS to WebAssembly so that we avoid having a dependency on a native module that's a pain for users to install Decktape. Otherwise, forking it should enable us to solve the issue, unless we find another library to manipulate PDF files.

**Comment by astefanutti** [comment]
@nicojs let me close this and follow-up on #201. Thanks again for the report.
