### ISSUE TITLE
export using reveal.js does not stop after the last slide

### ISSUE THREAD

**Issue by dirk-thomas** [astefanutti/decktape#23]
When invoking decktape on a slide set the progress shows e.g. 10 slides but keeps counting up indefinitely.

As a workaround I currently use the `generic` command instead which works fine for me.

**Comment by astefanutti** [comment]
Could you precise the reveal.js version you're using? Would that be possible for you to share the presentation for which you face the issue so that I can identify the root cause?

**Comment by dirk-thomas** [comment]
I am using the latest released version of reveal.js (3.1.0).

Based on your comment I have boiled down my slides to a minimum example: https://gist.github.com/dirk-thomas/e184539d8db4144f294e

The problematic items seems to be the `div` after the last slide (https://gist.github.com/dirk-thomas/e184539d8db4144f294e#file-example-html-L48). If I remove that div the export finishes correctly.

In my full slides I use this together with some css to add a company logo at the bottom left of each slide. Maybe there is a better way to achieve that?

**Comment by astefanutti** [comment]
Thanks for the details. It's enough for troubleshooting. DeckTape relies on the `Reveal.isLastSlide` API to check whether it should navigate to the next slide, see: https://github.com/astefanutti/decktape/blob/12a7813aabf34131d426046b0d0a0a341b03e385/plugins/reveal.js#L41.

So chances are the issue is actually on reveal.js API implementation side. I'll revert back to you when I have a confirmation whether that's a DeckTape or reveal.js issue.

**Comment by dirk-thomas** [comment]
Thank you for your fast feedback. I have filled com/hakimel/reveal.js#1366 as a replacement.

Btw. moving the extra different in front of all slide sections made it work for me too.
