### ISSUE TITLE
32-bit version of Windows PhantomJS binary

### ISSUE THREAD

**Issue by slickplaid** [astefanutti/decktape#55]
Is there any way we could get a 32-bit version of the binary for windows available? Our enterprise has 32-bit windows installed and won't let us install visual studio or compilation tools to build it ourselves.

Any help would be appreciated. Thanks!

**Comment by astefanutti** [comment]
It's been a while since I've compiled the Windows version so I don't remember what exact target platform I used to produce the `phantomjs-msvc2013-win64.exe` binary. It may be that I used the _AnyCPU_ target so that you could give that binary a try on 32-bit Windows.

Otherwise, I don't have a Windows box readily available to kick a new build unfortunately, though I'll have to get a new one sooner or later.

**Comment by astefanutti** [comment]
Available in `1.0.0` release, see `phantomjs-msvc2013-x86.exe` attachment.

**Comment by zhiying8710** [comment]
phantomjs-msvc2013-x86.exe dont support xp!

**Comment by SergiosGarcia** [comment]
Hi all here , well im from argentina , im looking for the 2.5 beta for win 32 please
can you compile for both system 32 and 64 always, because is a greate aplication , take care i hope you can compile for 32 bith too.

**Comment by eladkarako** [comment]
no official x86 (32 bit).
last stable is https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-windows.zip
latest is https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.5.0-beta2-windows.zip  
or you can try SlimerJs as an alternative.

you basically need to migrate to using a headless browser and maybe selenium.
https://developers.google.com/web/updates/2017/04/headless-chrome
https://www.selenium.dev/

I would recommend using a portable copy of chromium from 
https://github.com/Hibbiki/chromium-win64/releases
or https://github.com/Hibbiki/chromium-win32/releases

you can choose ungoogled, or sync if you need google account functionality, 
and `"--user-data-dir=C:\MySoftware\Chromium\profile"` can give you a specific folder for the profile so it won't write stuff under your user profile.

without selenium, that can give you all the basic functionality you need (all chrome command-line are supported) and even screenshots and web-extensions, and executing script (obviously opening real websites as well).

<hr/>

selenium can hook into the debug port of the headless mode (which is preferred since it is really fast and has no UI),  
or work in full browser mode (selenium controls mouse, keyboard using native binaries compiled to your os) which then closes the browser and returns whatever answer you need.

<hr/>

selenium is really bulky, and buggy. headless browser (firefox has that too) is your best alternative.
