### ISSUE TITLE
Kerning issues on CentOS 6

### ISSUE THREAD

**Issue by abecks** [astefanutti/decktape#60]
Trying to use your custom build of PhantomJS 2 to generate PDFs. I am running into issues where the kerning is messed up on Linux (CentOS 6) where it is fine on OS X.

OSX: http://i.imgur.com/FAwKIFR.png
CentoS: http://i.imgur.com/FttX4XO.png

PhantomJS 1.9.8 doesn't work with web fonts, installing the font locally does not work either
PhantomJS 2.1 release doesn't support multiple pages
PhantomJS 2 master doesn't support multiple pages
Decktape's custom PhantomJS almost works, but with font kerning issues, its the closest I've been able to get.

Trying to get PhantomJS working properly has been the most frustrating thing I've ever done in my life. Should I try switching to Ubuntu or give up and user Slimer?

**Comment by astefanutti** [comment]
I would guess there is still a couple of issues related to font rendering on Linux that may be linked to #3 (and hopefully solved with). You can go through the discussion, though the current status can be tracked with https://github.com/ariya/phantomjs/issues/13997#issuecomment-217982183 and [QTBUG-52417](https://bugreports.qt.io/browse/QTBUG-52417).

I can understand your frustration given the amount of effort I've also put into this (see https://github.com/astefanutti/decktape#phantomjs-fork). You may indeed want to give [SlimerJS](https://slimerjs.org) or [Nightmare](http://www.nightmarejs.org) a try. That being said, PhantomJS dev team is currently investing a lot of effort integrating a recent version of WebKit which might hopefully solve a lot of issues (see ariya/phantomjs#14386).

As this is not strictly related to DeckTape, I'm going to close this, though you can track progress on the font rendering issues on Linux mentioned above.

**Comment by ricokahler** [comment]
@abecks I have a patch for the multiple page issue. The issue lies within QtWebkit so the patch is split into to repos. Once the phantomJS 2.5 stuff gets sorted out then I'll probably add a small pull request upstream to Qt but for now you can use this patch if you still need it. It might solve your issue.

[The WebKit patch](https://github.com/ricokahler/qtwebkit/tree/switch-qwebframe-print-to-qpagedpaintdevice)
[The PhantomJS patch](https://github.com/ricokahler/phantomjs/tree/multipaged-pdf-fix)

The benefit of this patch is that the `renderBase64('pdf')` method now works as expected. This is great for me because I plan to use PhantomJS to convert webpages to PDFs. Now the PDF never hits the disk :D
