### ISSUE TITLE
Not working with remark?

### ISSUE THREAD

**Issue by sinedied** [astefanutti/decktape#92]
When I try to convert a slideshow made with remark, I get this error:
```
Loading page finished with status: success
Error: Unable to activate the Remark JS DeckTape plugin for the address: ...
```

I'm using the latest stable version of remark from there: `https://remarkjs.com/downloads/remark-latest.min.js`

Did I miss anything?

**Comment by astefanutti** [comment]
I've just tested with the _official_ Remark presentation (which uses `https://remarkjs.com/downloads/remark-latest.min.js`) and it works:

```
$ ./phantomjs https://remarkjs.com/ test.pdf
Loading page https://remarkjs.com/ ...
Loading page finished with status: success
Remark JS DeckTape plugin activated
Printing slide #19      (19/19) ...
Printed 19 slides
```

What command and DeckTape version do you use? Would you be able to share the presentation you're trying to export so that I can reproduce?

**Comment by sinedied** [comment]
I tried with a fresh decktape 1.0.0 setup.

Here is an example presentation failing: [test.html.zip](https://github.com/astefanutti/decktape/files/909662/test.html.zip)

The remark script is inlined from `https://remarkjs.com/downloads/remark-latest.min.js`.

The markdown is inlined from just this:
```markdown
title: test remark

# This is a test
lorem ipsum...

---

# Another slide
lorem ipsum...
```

**Comment by astefanutti** [comment]
The typical way DeckTape detects RemarkJS presentation requires having the `remark` and `slideshow` global variables defined. See [plugins/remark.js#L14](https://github.com/astefanutti/decktape/blob/4f43673ee5ce53eaf4672aa9316d9b1d65b780dd/plugins/remark.js#L14). This is what does the `remark-latest.min.js`.

The issue is likely due to the way the remark script is inlined in the presentation. One way to fix it is to mimic the way the original remark script is exposing its contract API.

**Comment by sinedied** [comment]
Ok from your I understand what's missing: the global `slideshow` variable was not there, hence the remarkjs mode not enabled. The inlining has nothing to do with that :)

Once fixed, this works as expected so I close this issue, thanks for the hint 👍
