### ISSUE TITLE
Tables with linear gradient background do not render correctly

### ISSUE THREAD

**Issue by yumweb** [astefanutti/decktape#98]
Hi There!

I am creating a PDF with Shower Framework. There is a table in the HTML file. Only the last row in the table is being rendered when the PDF is viewed on Chrome. The table appears to be fine when the PDF is viewed on a normal viewer. Attached is the image of the issue.

Below is the HTML used

```
<table>
	<tr>
		<th scope="col">Locavore</th>
		<th>Umami</th>
		<th>Helvetica</th>
		<th>Vegan</th>
	</tr>
	<tr>
		<th scope="row">Fingerstache</th>
		<td>Kale</td>
		<td>Chips</td>
		<td>Keytar</td>
	</tr>
	<tr>
		<th scope="row">Sriracha</th>
		<td>Gluten-free</td>
		<td>Ennui</td>
		<td>Keffiyeh</td>
	</tr>
	<tr>
		<th scope="row">Thundercats</th>
		<td>Jean</td>
		<td>Shorts</td>
		<td>Biodiesel</td>
	</tr>
	<tr>
		<th scope="row">Terry</th>
		<td>Richardson</td>
		<td>Swag</td>
		<td>Blog</td>
	</tr>
</table>
```

![image](https://user-images.githubusercontent.com/13010493/28116711-f35807a8-6727-11e7-9f1a-f21c4be354a7.png)

**Comment by astefanutti** [comment]
I've tested exporting the table above and open the produced PDF with Chrome and haven't been able to reproduce. So I suspect this has to do with something more specific to your presentation. Would you be able to share a minimal presentation that I could use to try reproduce?

On the other hand, Shower is supposed to provide PDF export out of the box, as documented in [github.com/shower/shower/docs/printing.md](https://github.com/shower/shower/blob/8c6ede75f496072bce6f56717e6997b521614c25/docs/printing.md). Could you try that approach and check the result?

Otherwise, it may be an issue at the level of the Chrome PDF reader. It tends to behave differently from Acrobat PDF reader.

**Comment by yumweb** [comment]
Hi Antonin,

Thanks for your reply. I looked at it carefully and noticed that the content in the table is being printed in the PDF but Chrome PDF viewer is applying a Black background to all the cells _except_ for the last row and `<th>` if present.

Here is the sample HTML used — [html.zip](https://github.com/astefanutti/decktape/files/1148673/html.zip) and the PDF generated from DeckTape — [1500041905756.pdf](https://github.com/astefanutti/decktape/files/1148676/1500041905756.pdf)

I did a `Cmd P` with the HTML and exported the PDF and it worked perfectly. Here is the PDF generated from this approach as well named — [pdf_with_cmd_p.pdf](https://github.com/astefanutti/decktape/files/1148707/pdf_with_ctrl_p.pdf)

FYI I am trying on the following:

macOS Sierra - Version 10.12.3 (16D32)
Google Chrome - Version 59.0.3071.115 (Official Build) (64-bit)
DeckTape Docker Image - astefanutti/decktape latest

Let me know if you need any other information.

Many Thanks!

**Comment by astefanutti** [comment]
Thanks a lot for the detailed use case. I've been able to reproduce.

It seems it is caused by the linear gradient background in your styles:

```
.slide table tr:not(:last-of-type) > * {
   background: -webkit-linear-gradient(
      bottom,
      #bdbdbd .055em,
      transparent .055em
    )
    repeat-x;
  background: linear-gradient(to top, #bdbdbd .055em, transparent .055em)
    repeat-x; 
}
```

Removing it makes the presentation exporting fine.

Linear gradient rendering in PDF is still problematic in PhantomJS and already affects DeckTape (#61).

Let me know if that's acceptable to change the background style as a work-around solution.

**Comment by yumweb** [comment]
Ah! I don't know why did I not check the styles on the tables. Actually I was using the Vanilla Shower template. The Shower template itself is shipping the styles with linear-gradient properties. Hence the confusion

https://shwr.me/shower/themes/ribbon/styles/screen-16x10.css
https://shwr.me/shower/themes/material/styles/screen-16x10.css

Anyways, this is perfectly acceptable and my PDF's are generating perfectly fine. Thanks for taking out time to check the issue. Appreciate a lot Antonin!

**Comment by astefanutti** [comment]
I'm glad it works for you!
